### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by matbi** [MCSPitaya/PitayaServer#3] opened 2018-04-23 09:43 UTC
User Story: As a lawyer, I want to receive notifications so that I can instantly see changes to case files

**Comment by ksmonkey123** [comment] 2018-05-01 19:52
Central Activity Tracking Table that can be filtered and requested with pagination. Base Framework rather simple, tracking must be added to every (relevant) endpoint

**Comment by ksmonkey123** [comment] 2018-05-01 20:02
Added This ticket to the sprint as it is essentially a duplicate of #4 and is more accurate than that one

**Comment by ksmonkey123** [comment] 2018-05-04 18:52
file functions now create notifications. Therefore all relevant actions currently present have notifications. More can be added as needed

**Closed by ksmonkey123** 2018-05-04 18:52 UTC
Labels: feature
